Repository TCU-ClassifAI/classifAI, pull requests merged in 2023-11, with the labels that each got.

#20 tabulated the content in submission
  frontend/src/Main/Submission/Submission.css
  frontend/src/Main/Submission/submission.js
Labels: enhancement

#25 Add WordCloud visualization to submission screen
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Main/Submission/WordCloud.js
  frontend/src/Main/Submission/submission.js
Labels: enhancement, feature

#37 NOTICKET: Update favicons and metadata in public folder
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
Labels: bug, documentation
